name: Discord Failure Alert

on:
  workflow_run:
    workflows: ["Sniffer Cron"]
    types:
      - completed

jobs:
  notify:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord alert
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}
        run: |
          curl -H "Content-Type: application/json" -d "{\"content\":\"❌ Sniffer workflow failed: $RUN_URL\"}" $DISCORD_WEBHOOK
