# .github/workflows/sniffer.yml
name: Sniffer Cron

on:
  schedule:
    - cron: "*/30 * * * *"        # 30 분마다(정각·30분)
  workflow_dispatch:              # 수동 실행 버튼

jobs:
  sniff:
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL:           ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
      TWITTER_BEARER:         ${{ secrets.TWITTER_BEARER }}
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: run sniffer
        run: deno run --allow-net --allow-env scripts/sniffer_or.ts
